import { ClerkProvider } from "@clerk/nextjs";
import "./globals.css";
import { Sour_Gummy } from "next/font/google";
import Provider from "../provider";
import { ThemeProvider } from "@/components/providers/theme-provider";
import { Toaster } from "sonner";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const sourGummy = Sour_Gummy({
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  style: ["normal", "italic"],
  subsets: ["latin"],
  variable: "--font-sour-gummy",
});

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={sourGummy.className}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <ClerkProvider>
            <Provider>
              {children}
              <Toaster />
            </Provider>
          </ClerkProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
